name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 0 * * *"  # runs daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          USERNAME: SmitSatasiya

      - name: Commit & Push the generated files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A .
          git commit -m "generated" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.PAT }}@github.com/SmitSatasiya/SmitSatasiya.git HEAD:main
